### ISSUE TITLE
countrycode

### ISSUE THREAD

**Issue by ChrisBMain** [ChrisBMain/Trade.War#3]
Countrycode is not recognizing some of the country names in the datasets. I will construct a dataset with the problematic names in one column and recognizable names in the other column. Then I'll mutate the names and then run countrycode again.

**Comment by Chris-FSU** [comment]
This was fixed in the latest push. I used [this dataset](https://github.com/Chris-FSU/Trade.War/blob/master/data/names.and.codes.csv) and lines 35 - 39 of [this code](https://github.com/Chris-FSU/Trade.War/blob/master/R/wrangle.R).
